import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Common build options
const buildOptions = {
	bundle: true,
	minify: prod,
	sourcemap: prod ? false : "inline",
	target: "es2018",
	logLevel: "info",
};

// Create context for TypeScript
const context = await esbuild.context({
	...buildOptions,
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	outfile: "main.js",
});

// Create context for CSS
const cssContext = await esbuild.context({
	...buildOptions,
	entryPoints: ['src/styles.css'],
	outfile: 'styles.css',
});

if (prod) {
	await context.rebuild();
	await cssContext.rebuild();
	process.exit(0);
} else {
	await context.watch();
	await cssContext.watch();
}
